### ISSUE TITLE
Implement storage gas cost calculator and refund counter

### ISSUE THREAD

**Issue by lightclient** [quilt/eth1.0-specs#11]
^

**Comment by Bhargavasomu** [comment]
I believe the storage gas calculation is complete with the presence of `SSTORE` opcode implementation and `calculate_intrinsic_gas` functions. Please correct me if wrong.

I believe the refund counter for `SSTORE` is still to be implemented. I have implemented this and am yet to open a PR. But to execute the tests for the refund counter, it's required that the other opcodes are implemented. Hence I can't run the tests at this moment. I will currently add a TODO statement for this code mentioning that it's yet to be tested. We will revisit the testing of the refund counter, when the other opcodes are implemented.

**Comment by Bhargavasomu** [comment]
My previous statement was wrong. As per below screenshot, SSTORE uses different gas values based on the previous stored values.
![image](https://user-images.githubusercontent.com/15922456/123618175-92032000-d825-11eb-8d44-8591f1afedf7.png)

I'll add this feature right away.

**Comment by Bhargavasomu** [comment]
I have implemented the above feature as well

**Comment by Bhargavasomu** [comment]
Closed by #51
