### ISSUE TITLE
Patricialize the block txs

### ISSUE THREAD

**Issue by lightclient** [quilt/eth1.0-specs#12]
Should also verify the trie root matches the block being processed.

**Comment by Bhargavasomu** [comment]
I'll check this out and try to implement it.

**Comment by Bhargavasomu** [comment]
As part of this, I would also be doing the following

- Support RLP encoding and decoding for custom dataclasses
- Verify the ommers hash before state transitioning
- Verify the transaction root before state transitioning

/cc @lightclient @SamWilsn

**Comment by Bhargavasomu** [comment]
Closing this issue - Fixed by #49
