### ISSUE TITLE
Implement `*CALL` family

### ISSUE THREAD

**Issue by lightclient** [quilt/eth1.0-specs#15]
^

**Comment by Bhargavasomu** [comment]
I would like to work on this. Please let me know if anyone else is working on this. Thanks.

**Comment by voith** [comment]
@Bhargavasomu  I wonder how you'll implement the call family without memory management being implemented.  I'm planning to add the foundation for memory management in #10. So I'm not sure if this is a good issue to pick right now.

**Comment by lightclient** [comment]
closed for: https://github.com/ethereum/eth1.0-specs/issues/230
