### ISSUE TITLE
Decorator to ignore lines from docs

### ISSUE THREAD

**Issue by lightclient** [quilt/eth1.0-specs#31]
I'd like to implement EVM tracing, but not have that code show in the docs.

**Comment by SamWilsn** [comment]
I am not super familiar with EVM tracing, but do you think it'd be possible to use a decorator to implement tracing (as opposed to hiding docs)?

Maybe something like:

```python
from eth1spec.tracing import trace_evm

@trace_evm
def add():
    pass
```

**Comment by lightclient** [comment]
moved to https://github.com/ethereum/eth1.0-specs/issues/235
