### ISSUE TITLE
Document code and style conventions

### ISSUE THREAD

**Issue by SamWilsn** [quilt/eth1.0-specs#42]
We should formalize any coding or style decisions not covered by `black` into a document somewhere in the repository.

For now, this issue can be a temporary place to collect these kind of decisions:

 - Name functions with short imperative phrases, avoiding extra words which don't add information (choose `fetch` instead of `do_fetch`).
 - Use exceptions for errors which are handled in-protocol (ex. `OutOfGas`), and `assert` for everything else.
 - Never use `type: ignore` unless absolutely necessary.

**Comment by lightclient** [comment]
here's a good place to get inspiration: https://github.com/ethereum/snake-charmers-tactical-manual/blob/4dc11553939675e427e5daec51665033b0777538/naming-things.md#prefixes

**Comment by lightclient** [comment]
moved to https://github.com/ethereum/eth1.0-specs/issues/237
