### ISSUE TITLE
Implement the Proof of Work Algorithm

### ISSUE THREAD

**Issue by voith** [quilt/eth1.0-specs#43]
### What was missing?
We need to implement`EthHash`, the proof of work algorithm. 

### How can this be fixed?
- Refer to this [link](https://eth.wiki/en/concepts/ethash/ethash) for details and test cases.
- Refer to this [implementation](https://github.com/ethereum/ethash) to see if some code can be borrowed.

**Comment by voith** [comment]
Somethings to consider: Looking at this [implementation](https://github.com/ethereum/ethash/blob/master/src/python/core.c) I can't help notice that its implemented in `C`, because efficiency is key. I'm not sure how much time it'll take to run Ethereum test fixtures with a pure python implementation. But then again readability is key to this project.

**Comment by SamWilsn** [comment]
Yeah, performance is definitely going to be interesting. We've set the project up so that it can run on CPython and PyPy. Hopefully the JIT will be enough to make up for some of the slowness, but if not, I guess we can look at Cython too.

**Comment by lightclient** [comment]
moved to https://github.com/ethereum/eth1.0-specs/issues/238
