### ISSUE TITLE
Consider using Enum for Nibbles type

### ISSUE THREAD

**Issue by pipermerriam** [quilt/eth1.0-specs#54]
Currently, the `trie` implementation uses a `bytes` type for the sequence of nibbles, with the stated validation rules that each byte may be no larger than 15.  This requirement doesn't appear to actually be enforced **and** it would be ideal if the type definitions actually constrained the inputs via the type system rather than runtime validation.

I would suggest using an `enum.IntEnum` for this:

```python
class Nibble(enum.IntEnum):
    NIBBLE_0 = 0x0
    NIBBLE_1 = 0x1
    ...
    NIBBLE_F = 0xf

Nibbles = List[Nibble]
```

Not only will this give you strong guarantees on anything that needs to take a `Nibbles` type as an input, but it also lets you have runtime validation for free

```python
def bytes_to_nibbles(value: bytes) -> Nibbles:
    return [Nibble(v) for v in value]  # will raise a TypeError if the value isn't part of the Enum)
```

**Comment by lightclient** [comment]
moved to https://github.com/ethereum/eth1.0-specs/issues/241
